"""Closed-profile structural facts from ECMA-376 transitional SpreadsheetML.

Reference: ECMA-376 fourth-edition transitional sml.xsd and shared simple types,
mirrored in docx4j at commit 0eec2587ab38db5265ce66c12423849c1bea2c60:
xsd/sml/sml_ECMA376_4ed_transitional.xsd and xsd/shared/shared-commonSimpleTypes.xsd.
These tables describe only our accepted elements/attributes, with explicit
profile compatibility for ISO-date cells and the inert showInk flag. No schema
download or XML evaluation occurs at runtime. Keep enum, required-field, and
cardinality tests beside changes.
"""

from __future__ import annotations

_SIMPLE_GROUPS = {
    "boolean": {
        "sheetPr": "syncHorizontal syncVertical transitionEvaluation transitionEntry "
        "published filterMode enableFormatConditionsCalculation",
        "tabColor": "auto",
        "outlinePr": "applyStyles summaryBelow summaryRight showOutlineSymbols",
        "pageSetUpPr": "autoPageBreaks fitToPage",
        "sheetView": "windowProtection showFormulas showGridLines showRowColHeaders showZeros "
        "rightToLeft tabSelected showRuler showOutlineSymbols defaultGridColor "
        "showWhiteSpace",
        "sheetFormatPr": "customHeight zeroHeight thickTop thickBottom",
        "col": "hidden bestFit customWidth phonetic collapsed",
        "row": "customFormat hidden customHeight collapsed thickTop thickBot ph",
        "c": "ph",
        "f": "aca ca bx",
        "b": "val",
        "i": "val",
        "strike": "val",
        "outline": "val",
        "shadow": "val",
        "condense": "val",
        "extend": "val",
        "color": "auto",
        "sheetProtection": "sheet objects scenarios formatCells formatColumns formatRows "
        "insertColumns insertRows insertHyperlinks deleteColumns "
        "deleteRows selectLockedCells sort autoFilter pivotTables "
        "selectUnlockedCells",
        "filterColumn": "hiddenButton showButton",
        "filters": "blank",
        "top10": "top percent",
        "customFilters": "and",
        "colorFilter": "cellColor",
        "sortState": "columnSort caseSensitive",
        "sortCondition": "descending",
        "printOptions": "horizontalCentered verticalCentered headings gridLines gridLinesSet",
        "pageSetup": "usePrinterDefaults blackAndWhite draft useFirstPageNumber",
        "headerFooter": "differentOddEven differentFirst scaleWithDoc alignWithMargins",
        "brk": "man pt",
        "ignoredError": "evalError twoDigitTextYear numberStoredAsText formula formulaRange "
        "unlockedFormula emptyCellReference listDataValidation "
        "calculatedColumn",
        "workbookPr": "date1904 showBorderUnselectedTables filterPrivacy promptedSolutions showInk "
        "backupFile saveExternalLinkValues hidePivotFieldList "
        "showPivotChartFilter allowRefreshQuery autoCompressPictures "
        "refreshAllConnections",
        "workbookProtection": "lockStructure lockWindows lockRevision",
        "workbookView": "minimized showHorizontalScroll showVerticalScroll showSheetTabs "
        "autoFilterDateGrouping",
        "definedName": "hidden function vbProcedure xlm publishToServer workbookParameter",
        "calcPr": "fullCalcOnLoad iterate fullPrecision calcCompleted calcOnSave "
        "concurrentCalc forceFullCalc",
        "fgColor": "auto",
        "bgColor": "auto",
        "border": "diagonalUp diagonalDown outline",
        "xf": "quotePrefix pivotButton applyNumberFormat applyFont applyFill applyBorder "
        "applyAlignment applyProtection",
        "alignment": "wrapText justifyLastLine shrinkToFit",
        "protection": "locked hidden",
        "cellStyle": "hidden customBuiltin",
        "tableStyle": "pivot table",
        "table": "insertRow insertRowShift totalsRowShown published",
        "calculatedColumnFormula": "array",
        "totalsRowFormula": "array",
        "tableStyleInfo": "showFirstColumn showLastColumn showRowStripes showColumnStripes",
    },
    "string": {
        "sheetPr": "syncRef codeName",
        "dimension": "ref",
        "sheetView": "view topLeftCell",
        "pane": "topLeftCell activePane state",
        "selection": "pane activeCell",
        "c": "r t",
        "f": "t ref",
        "phoneticPr": "type alignment",
        "rFont": "val",
        "u": "val",
        "vertAlign": "val",
        "scheme": "val",
        "sheetProtection": "algorithmName",
        "autoFilter": "ref",
        "filters": "calendarType",
        "filter": "val",
        "dateGroupItem": "dateTimeGrouping",
        "customFilter": "operator val",
        "dynamicFilter": "type",
        "iconFilter": "iconSet",
        "sortState": "sortMethod ref",
        "sortCondition": "sortBy ref customList iconSet",
        "mergeCell": "ref",
        "pageSetup": "pageOrder orientation cellComments errors",
        "hyperlink": "ref location tooltip display",
        "fileVersion": "appName lastEdited lowestEdited rupBuild",
        "workbookPr": "showObjects updateLinks codeName",
        "workbookProtection": "revisionsAlgorithmName workbookAlgorithmName",
        "workbookView": "visibility",
        "sheet": "name state",
        "definedName": "name comment customMenu description help statusBar shortcutKey",
        "calcPr": "calcMode refMode",
        "numFmt": "formatCode",
        "name": "val",
        "patternFill": "patternType",
        "gradientFill": "type",
        "left": "style",
        "right": "style",
        "top": "style",
        "bottom": "style",
        "start": "style",
        "end": "style",
        "diagonal": "style",
        "vertical": "style",
        "horizontal": "style",
        "alignment": "horizontal vertical",
        "cellStyle": "name",
        "tableStyles": "defaultTableStyle defaultPivotStyle",
        "tableStyle": "name",
        "tableStyleElement": "type",
        "table": "name displayName comment ref tableType headerRowCellStyle dataCellStyle "
        "totalsRowCellStyle",
        "tableColumn": "uniqueName name totalsRowFunction totalsRowLabel headerRowCellStyle "
        "dataCellStyle totalsRowCellStyle",
        "tableStyleInfo": "name",
    },
    "unsignedInt": {
        "tabColor": "indexed theme",
        "sheetView": "colorId zoomScale zoomScaleNormal zoomScaleSheetLayoutView "
        "zoomScalePageLayoutView workbookViewId",
        "selection": "activeCellId",
        "sheetFormatPr": "baseColWidth",
        "col": "min max style",
        "row": "r s",
        "c": "s cm vm",
        "f": "si",
        "rPh": "sb eb",
        "phoneticPr": "fontId",
        "color": "indexed theme",
        "sheetProtection": "spinCount",
        "filterColumn": "colId",
        "colorFilter": "dxfId",
        "iconFilter": "iconId",
        "sortCondition": "dxfId iconId",
        "mergeCells": "count",
        "pageSetup": "paperSize scale firstPageNumber fitToWidth fitToHeight "
        "horizontalDpi verticalDpi copies",
        "rowBreaks": "count manualBreakCount",
        "colBreaks": "count manualBreakCount",
        "brk": "id min max",
        "tableParts": "count",
        "workbookPr": "defaultThemeVersion",
        "workbookProtection": "revisionsSpinCount workbookSpinCount",
        "workbookView": "windowWidth windowHeight tabRatio firstSheet activeTab",
        "sheet": "sheetId",
        "definedName": "localSheetId functionGroupId",
        "calcPr": "calcId iterateCount concurrentManualCount",
        "sst": "count uniqueCount",
        "numFmts": "count",
        "numFmt": "numFmtId",
        "fonts": "count",
        "fills": "count",
        "fgColor": "indexed theme",
        "bgColor": "indexed theme",
        "borders": "count",
        "cellStyleXfs": "count",
        "cellXfs": "count",
        "xf": "numFmtId fontId fillId borderId xfId",
        "alignment": "textRotation indent readingOrder",
        "cellStyles": "count",
        "cellStyle": "xfId builtinId iLevel",
        "dxfs": "count",
        "tableStyles": "count",
        "tableStyle": "count",
        "tableStyleElement": "size dxfId",
        "table": "id headerRowCount totalsRowCount headerRowDxfId dataDxfId "
        "totalsRowDxfId headerRowBorderDxfId tableBorderDxfId "
        "totalsRowBorderDxfId connectionId",
        "tableColumns": "count",
        "tableColumn": "id headerRowDxfId dataDxfId totalsRowDxfId",
    },
    "hexBinary": {
        "tabColor": "rgb",
        "color": "rgb",
        "sheetProtection": "password",
        "workbookProtection": "workbookPassword revisionsPassword",
        "fgColor": "rgb",
        "bgColor": "rgb",
        "rgbColor": "rgb",
    },
    "double": {
        "tabColor": "tint",
        "pane": "xSplit ySplit",
        "sheetFormatPr": "defaultColWidth defaultRowHeight",
        "col": "width",
        "row": "ht",
        "color": "tint",
        "sz": "val",
        "top10": "val filterVal",
        "dynamicFilter": "val maxVal",
        "pageMargins": "left right top bottom header footer",
        "calcPr": "iterateDelta",
        "fgColor": "tint",
        "bgColor": "tint",
        "gradientFill": "degree left right top bottom",
        "stop": "position",
    },
    "ST_Sqref": {"selection": "sqref", "ignoredError": "sqref"},
    "unsignedByte": {
        "sheetFormatPr": "outlineLevelRow outlineLevelCol",
        "col": "outlineLevel",
        "row": "outlineLevel",
    },
    "ST_CellSpans": {"row": "spans"},
    "int": {"charset": "val", "workbookView": "xWindow yWindow", "alignment": "relativeIndent"},
    "integer": {"family": "val"},
    "base64Binary": {
        "sheetProtection": "hashValue saltValue",
        "workbookProtection": "revisionsHashValue revisionsSaltValue workbookHashValue "
        "workbookSaltValue",
    },
    "unsignedShort": {"dateGroupItem": "year month day hour minute second"},
    "token": {"fileVersion": "codeName"},
}

SIMPLE_TYPES = {
    (tag, attribute): kind
    for kind, tags in _SIMPLE_GROUPS.items()
    for tag, attributes in tags.items()
    for attribute in attributes.split()
}

_ENUM_GROUPS = {
    "normal pageBreakPreview pageLayout": (("sheetView", "view"),),
    "bottomRight topRight bottomLeft topLeft": (("pane", "activePane"), ("selection", "pane")),
    "split frozen frozenSplit": (("pane", "state"),),
    # The approved adapter profile also supports literal ISO-date cells (d).
    "b n e s str inlineStr d": (("c", "t"),),
    "normal array dataTable shared": (("f", "t"),),
    "halfwidthKatakana fullwidthKatakana Hiragana noConversion": (("phoneticPr", "type"),),
    "noControl left center distributed": (("phoneticPr", "alignment"),),
    "single double singleAccounting doubleAccounting none": (("u", "val"),),
    "baseline superscript subscript": (("vertAlign", "val"),),
    "none major minor": (("scheme", "val"),),
    "gregorian gregorianUs gregorianMeFrench gregorianArabic hijri hebrew taiwan japan thai korea saka gregorianXlitEnglish gregorianXlitFrench none": (
        ("filters", "calendarType"),
    ),
    "year month day hour minute second": (("dateGroupItem", "dateTimeGrouping"),),
    "equal lessThan lessThanOrEqual notEqual greaterThanOrEqual greaterThan": (
        ("customFilter", "operator"),
    ),
    "null aboveAverage belowAverage tomorrow today yesterday nextWeek thisWeek lastWeek nextMonth thisMonth lastMonth nextQuarter thisQuarter lastQuarter nextYear thisYear lastYear yearToDate Q1 Q2 Q3 Q4 M1 M2 M3 M4 M5 M6 M7 M8 M9 M10 M11 M12": (
        ("dynamicFilter", "type"),
    ),
    "3Arrows 3ArrowsGray 3Flags 3TrafficLights1 3TrafficLights2 3Signs 3Symbols 3Symbols2 4Arrows 4ArrowsGray 4RedToBlack 4Rating 4TrafficLights 5Arrows 5ArrowsGray 5Rating 5Quarters": (
        ("iconFilter", "iconSet"),
        ("sortCondition", "iconSet"),
    ),
    "stroke pinYin none": (("sortState", "sortMethod"),),
    "value cellColor fontColor icon": (("sortCondition", "sortBy"),),
    "downThenOver overThenDown": (("pageSetup", "pageOrder"),),
    "default portrait landscape": (("pageSetup", "orientation"),),
    "none asDisplayed atEnd": (("pageSetup", "cellComments"),),
    "displayed blank dash NA": (("pageSetup", "errors"),),
    "all placeholders none": (("workbookPr", "showObjects"),),
    "userSet never always": (("workbookPr", "updateLinks"),),
    "visible hidden veryHidden": (("workbookView", "visibility"), ("sheet", "state")),
    "manual auto autoNoTable": (("calcPr", "calcMode"),),
    "A1 R1C1": (("calcPr", "refMode"),),
    "none solid mediumGray darkGray lightGray darkHorizontal darkVertical darkDown darkUp darkGrid darkTrellis lightHorizontal lightVertical lightDown lightUp lightGrid lightTrellis gray125 gray0625": (
        ("patternFill", "patternType"),
    ),
    "linear path": (("gradientFill", "type"),),
    "none thin medium dashed dotted thick double hair mediumDashed dashDot mediumDashDot dashDotDot mediumDashDotDot slantDashDot": (
        ("left", "style"),
        ("right", "style"),
        ("top", "style"),
        ("bottom", "style"),
        ("start", "style"),
        ("end", "style"),
        ("diagonal", "style"),
        ("vertical", "style"),
        ("horizontal", "style"),
    ),
    "general left center right fill justify centerContinuous distributed": (
        ("alignment", "horizontal"),
    ),
    "top center bottom justify distributed": (("alignment", "vertical"),),
    "wholeTable headerRow totalRow firstColumn lastColumn firstRowStripe secondRowStripe firstColumnStripe secondColumnStripe firstHeaderCell lastHeaderCell firstTotalCell lastTotalCell firstSubtotalColumn secondSubtotalColumn thirdSubtotalColumn firstSubtotalRow secondSubtotalRow thirdSubtotalRow blankRow firstColumnSubheading secondColumnSubheading thirdColumnSubheading firstRowSubheading secondRowSubheading thirdRowSubheading pageFieldLabels pageFieldValues": (
        ("tableStyleElement", "type"),
    ),
    "worksheet xml queryTable": (("table", "tableType"),),
    "none sum min max average count countNums stdDev var custom": (
        ("tableColumn", "totalsRowFunction"),
    ),
}

ENUMERATIONS = {
    key: frozenset(values.split()) for values, keys in _ENUM_GROUPS.items() for key in keys
}

REQUIRED_ATTRIBUTES = {
    "dimension": ("ref",),
    "sheetView": ("workbookViewId",),
    "sheetFormatPr": ("defaultRowHeight",),
    "col": ("min", "max"),
    "rPh": ("sb", "eb"),
    "phoneticPr": ("fontId",),
    "rFont": ("val",),
    "charset": ("val",),
    "family": ("val",),
    "sz": ("val",),
    "vertAlign": ("val",),
    "scheme": ("val",),
    "filterColumn": ("colId",),
    "dateGroupItem": ("year", "dateTimeGrouping"),
    "top10": ("val",),
    "dynamicFilter": ("type",),
    "iconFilter": ("iconSet",),
    "sortState": ("ref",),
    "sortCondition": ("ref",),
    "mergeCell": ("ref",),
    "pageMargins": ("left", "right", "top", "bottom", "header", "footer"),
    "ignoredError": ("sqref",),
    "hyperlink": ("ref",),
    "sheet": ("name", "sheetId"),
    "definedName": ("name",),
    "numFmt": ("numFmtId", "formatCode"),
    "name": ("val",),
    "stop": ("position",),
    "cellStyle": ("xfId",),
    "tableStyle": ("name",),
    "tableStyleElement": ("type",),
    "table": ("id", "displayName", "ref"),
    "tableColumn": ("id", "name"),
}

CHILD_COUNTS: dict[str, dict[str, tuple[int, int | None]]] = {
    "worksheet": {
        "sheetPr": (0, 1),
        "dimension": (0, 1),
        "sheetViews": (0, 1),
        "sheetFormatPr": (0, 1),
        "cols": (0, None),
        "sheetData": (1, 1),
        "sheetProtection": (0, 1),
        "autoFilter": (0, 1),
        "sortState": (0, 1),
        "mergeCells": (0, 1),
        "phoneticPr": (0, 1),
        "hyperlinks": (0, 1),
        "printOptions": (0, 1),
        "pageMargins": (0, 1),
        "pageSetup": (0, 1),
        "headerFooter": (0, 1),
        "rowBreaks": (0, 1),
        "colBreaks": (0, 1),
        "ignoredErrors": (0, 1),
        "tableParts": (0, 1),
    },
    "sheetPr": {"tabColor": (0, 1), "outlinePr": (0, 1), "pageSetUpPr": (0, 1)},
    "sheetViews": {"sheetView": (1, None)},
    "sheetView": {"pane": (0, 1), "selection": (0, 4)},
    "cols": {"col": (1, None)},
    "sheetData": {"row": (0, None)},
    "row": {"c": (0, None)},
    "c": {"f": (0, 1), "v": (0, 1), "is": (0, 1)},
    "is": {"t": (0, 1), "r": (0, None), "rPh": (0, None), "phoneticPr": (0, 1)},
    "si": {"t": (0, 1), "r": (0, None), "rPh": (0, None), "phoneticPr": (0, 1)},
    "r": {"rPr": (0, 1), "t": (1, 1)},
    "rPh": {"t": (1, 1)},
    "rPr": {
        "rFont": (0, None),
        "charset": (0, None),
        "family": (0, None),
        "b": (0, None),
        "i": (0, None),
        "strike": (0, None),
        "outline": (0, None),
        "shadow": (0, None),
        "condense": (0, None),
        "extend": (0, None),
        "color": (0, None),
        "sz": (0, None),
        "u": (0, None),
        "vertAlign": (0, None),
        "scheme": (0, None),
    },
    "autoFilter": {"filterColumn": (0, None), "sortState": (0, 1)},
    "filterColumn": {
        "filters": (0, 1),
        "top10": (0, 1),
        "customFilters": (0, 1),
        "dynamicFilter": (0, 1),
        "colorFilter": (0, 1),
        "iconFilter": (0, 1),
    },
    "filters": {"filter": (0, None), "dateGroupItem": (0, None)},
    "customFilters": {"customFilter": (1, 2)},
    "sortState": {"sortCondition": (0, 64)},
    "mergeCells": {"mergeCell": (1, None)},
    "headerFooter": {
        "oddHeader": (0, 1),
        "oddFooter": (0, 1),
        "evenHeader": (0, 1),
        "evenFooter": (0, 1),
        "firstHeader": (0, 1),
        "firstFooter": (0, 1),
    },
    "rowBreaks": {"brk": (0, None)},
    "colBreaks": {"brk": (0, None)},
    "ignoredErrors": {"ignoredError": (1, None)},
    "hyperlinks": {"hyperlink": (1, None)},
    "tableParts": {"tablePart": (0, None)},
    "workbook": {
        "fileVersion": (0, 1),
        "workbookPr": (0, 1),
        "workbookProtection": (0, 1),
        "bookViews": (0, 1),
        "sheets": (1, 1),
        "definedNames": (0, 1),
        "calcPr": (0, 1),
    },
    "bookViews": {"workbookView": (1, None)},
    "sheets": {"sheet": (1, None)},
    "definedNames": {"definedName": (0, None)},
    "sst": {"si": (0, None)},
    "styleSheet": {
        "numFmts": (0, 1),
        "fonts": (0, 1),
        "fills": (0, 1),
        "borders": (0, 1),
        "cellStyleXfs": (0, 1),
        "cellXfs": (0, 1),
        "cellStyles": (0, 1),
        "dxfs": (0, 1),
        "tableStyles": (0, 1),
        "colors": (0, 1),
    },
    "numFmts": {"numFmt": (0, None)},
    "fonts": {"font": (0, None)},
    "font": {
        "name": (0, None),
        "charset": (0, None),
        "family": (0, None),
        "b": (0, None),
        "i": (0, None),
        "strike": (0, None),
        "outline": (0, None),
        "shadow": (0, None),
        "condense": (0, None),
        "extend": (0, None),
        "color": (0, None),
        "sz": (0, None),
        "u": (0, None),
        "vertAlign": (0, None),
        "scheme": (0, None),
    },
    "fills": {"fill": (0, None)},
    "fill": {"patternFill": (0, 1), "gradientFill": (0, 1)},
    "patternFill": {"fgColor": (0, 1), "bgColor": (0, 1)},
    "gradientFill": {"stop": (0, None)},
    "stop": {"color": (1, 1)},
    "borders": {"border": (0, None)},
    "border": {
        "start": (0, 1),
        "end": (0, 1),
        "left": (0, 1),
        "right": (0, 1),
        "top": (0, 1),
        "bottom": (0, 1),
        "diagonal": (0, 1),
        "vertical": (0, 1),
        "horizontal": (0, 1),
    },
    "left": {"color": (0, 1)},
    "right": {"color": (0, 1)},
    "top": {"color": (0, 1)},
    "bottom": {"color": (0, 1)},
    "start": {"color": (0, 1)},
    "end": {"color": (0, 1)},
    "diagonal": {"color": (0, 1)},
    "vertical": {"color": (0, 1)},
    "horizontal": {"color": (0, 1)},
    "cellStyleXfs": {"xf": (1, None)},
    "cellXfs": {"xf": (1, None)},
    "xf": {"alignment": (0, 1), "protection": (0, 1)},
    "cellStyles": {"cellStyle": (1, None)},
    "dxfs": {"dxf": (0, None)},
    "dxf": {
        "font": (0, 1),
        "numFmt": (0, 1),
        "fill": (0, 1),
        "alignment": (0, 1),
        "border": (0, 1),
        "protection": (0, 1),
    },
    "tableStyles": {"tableStyle": (0, None)},
    "tableStyle": {"tableStyleElement": (0, None)},
    "colors": {"indexedColors": (0, 1), "mruColors": (0, 1)},
    "indexedColors": {"rgbColor": (1, None)},
    "mruColors": {"color": (1, None)},
    "table": {
        "autoFilter": (0, 1),
        "sortState": (0, 1),
        "tableColumns": (1, 1),
        "tableStyleInfo": (0, 1),
    },
    "tableColumns": {"tableColumn": (1, None)},
    "tableColumn": {"calculatedColumnFormula": (0, 1), "totalsRowFormula": (0, 1)},
}

CHILD_ORDER = {
    "worksheet": (
        "sheetPr",
        "dimension",
        "sheetViews",
        "sheetFormatPr",
        "cols",
        "sheetData",
        "sheetProtection",
        "autoFilter",
        "sortState",
        "mergeCells",
        "phoneticPr",
        "hyperlinks",
        "printOptions",
        "pageMargins",
        "pageSetup",
        "headerFooter",
        "rowBreaks",
        "colBreaks",
        "ignoredErrors",
        "tableParts",
    ),
    "sheetPr": ("tabColor", "outlinePr", "pageSetUpPr"),
    "sheetView": ("pane", "selection"),
    "c": ("f", "v", "is"),
    "is": ("t", "r", "rPh", "phoneticPr"),
    "si": ("t", "r", "rPh", "phoneticPr"),
    "r": ("rPr", "t"),
    "autoFilter": ("filterColumn", "sortState"),
    "filters": ("filter", "dateGroupItem"),
    "headerFooter": (
        "oddHeader",
        "oddFooter",
        "evenHeader",
        "evenFooter",
        "firstHeader",
        "firstFooter",
    ),
    "workbook": (
        "fileVersion",
        "workbookPr",
        "workbookProtection",
        "bookViews",
        "sheets",
        "definedNames",
        "calcPr",
    ),
    "styleSheet": (
        "numFmts",
        "fonts",
        "fills",
        "borders",
        "cellStyleXfs",
        "cellXfs",
        "cellStyles",
        "dxfs",
        "tableStyles",
        "colors",
    ),
    "patternFill": ("fgColor", "bgColor"),
    "border": (
        "start",
        "end",
        "left",
        "right",
        "top",
        "bottom",
        "diagonal",
        "vertical",
        "horizontal",
    ),
    "xf": ("alignment", "protection"),
    "dxf": ("font", "numFmt", "fill", "alignment", "border", "protection"),
    "colors": ("indexedColors", "mruColors"),
    "table": ("autoFilter", "sortState", "tableColumns", "tableStyleInfo"),
    "tableColumn": ("calculatedColumnFormula", "totalsRowFormula"),
}

INTEGER_RANGES = {("family", "val"): (0, 14)}

HEX_LENGTHS = {
    ("tabColor", "rgb"): 4,
    ("color", "rgb"): 4,
    ("sheetProtection", "password"): 2,
    ("workbookProtection", "workbookPassword"): 2,
    ("workbookProtection", "revisionsPassword"): 2,
    ("fgColor", "rgb"): 4,
    ("bgColor", "rgb"): 4,
    ("rgbColor", "rgb"): 4,
}

PATTERNS = {
    (
        "fileVersion",
        "codeName",
    ): "\\{[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}\\}"
}
